server:
  port: 8080
spring:
  freemarker:
    expose-spring-macro-helpers: true
    allow-request-override: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .html
    template-loader-path: classpath:/WEB-INF/view/
    request-context-attribute: ctx
    settings:
      classic_compatible: true
  profiles:
    active: @spring.active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
        - project-admin/src/main/java
        - static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.1.247:3306/zzsres?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-name: zzsres
    druid:
      filter: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
mybatis-plus:
  mapper-locations: classpath*:com/mapscience/modular/*/mapper/mappers/*.xml
  type-aliases-package: com.mapscience.modular.*.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true

project:
  swagger-open: true
  kaptcha-open: false
  spring-session-open: false
  session-invalidate-time: 1800
  session-validation-interval: 900
ftp:
  hostname: 192.168.1.228
  password: 123456
  username: administrator
  port: 21
  httpPath: http://192.168.1.228:8888
#jedis配置
redis:
  host: 192.168.1.225
  port: 6379
  password:
  timeout: 10000
  max-active: 200
  max-wait: -1
  max-idle: 8
  min-idle: 0




